[package]
name = "image-spider"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
md5 = { version = "0.8.0" }
reqwest = { version = "0.12.23", default-features = false, features =["rustls-tls"] }
tokio = { version = "1.47", features = ["fs", "rt", "rt-multi-thread", "macros"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
chrono = { version = "0.4.41" }
tracing-log = { version = "0.2.0" }
chrono-tz = { version = "0.10.4" }
owo-colors = { version = "4.2.2" }
log = { version = "0.4.27" }

[[bin]]
name = "image-spider"
path = "src/main.rs"
